blank_issues_enabled: true
contact_links:
  - name: Support Question
    url: https://discord.gg/ur573ZjARd
    about: Any questions or support needed regarding my cogs.
  - name: Private Support
    url: https://discord.gg/JmCFyq7
    about: Private questions about my cogs can be brought to my personal server.
